version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: financial_manager
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pkg: rust_financial_manager
    container_name: rust_app
    environment:
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_PORT: 8080
      ROCKET_URL: postgres://myuser:mypassword@postgres:5432/financial_manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d financial_manager -h postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  postgres_data:
