version: "3.7"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: financial_manager
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "${ROCKET_PORT:-8000}:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:your_password@db/financial_manager"
      ROCKET_SECRET_KEY: ${ROCKET_SECRET_KEY:-$(openssl rand -base64 32)}
      ROCKET_PORT: ${ROCKET_PORT:-8000}
    volumes:
      - .:/usr/src/app
    command: >
      sh -c " 
        # Install Diesel CLI
        cargo install diesel_cli --no-default-features --features postgres &&
        
        # Run Diesel setup and migrations
        diesel setup --database-url=$${DATABASE_URL} &&
        diesel migration run --database-url=$${DATABASE_URL} &&
        
        # Start the Rust application
        ROCKET_SECRET_KEY=$(openssl rand -base64 32) ROCKET_PORT=${ROCKET_PORT:-8000} /usr/local/bin/rust_financial_manager 
      "

volumes:
  db-data:
