[global]

[debug]
[default.databases.postgres_db]
url = "postgres://postgres:glpat-BYytBgysP3yeceKp6FUW@192.168.178.48/financial_manager"

[release]
[release.databases.postgres_db]
url = "postgres://myuser:mypassword@postgres:5432/financial_manager"
