name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  setup_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: |
          rustc --version
          cargo --version
          rustup component add clippy rustfmt
          cargo install cargo-tarpaulin cargo-audit
        working-directory: ./rust_financial_manager

  cargo_build_release:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Build with Cargo in Release Mode
        run: cargo build --release
        working-directory: ./rust_financial_manager

  run_tests_and_coverage:
    runs-on: ubuntu-latest
    needs: cargo_build_release
    steps:
      - uses: actions/checkout@v3
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Pull Docker image
        run: docker pull your-docker-image:latest
      - name: Run Tests and Coverage inside Docker container
        run: |
          docker run --env-file .env.ci your-docker-image:latest \
          /bin/bash -c "\
            cargo test --release && \
            cargo tarpaulin --release --engine llvm --ignore-tests --out Xml"
        working-directory: ./rust_financial_manager
      - name: Upload coverage to Codecov
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }} -f coverage.xml
        working-directory: ./rust_financial_manager
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  lint_and_format:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Lint and Format
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check
        working-directory: ./rust_financial_manager

  documentation_benchmarks_audit:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Documentation, Benchmarks, and Audit
        run: |
          cargo doc --no-deps
          cargo bench
          cargo audit --deny-warnings
        working-directory: ./rust_financial_manager
