name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        run: rustc --version && cargo --version
      - name: Install cargo-tarpaulin and cargo-audit
        run: cargo install cargo-tarpaulin cargo-audit

  build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo builds
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: target/debug

  test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: [setup, build]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: cargo test

  lint_format:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - name: Install Clippy and Rustfmt
        run: rustup component add clippy rustfmt
      - name: Lint Code
        run: cargo clippy -- -D warnings
      - name: Check Formatting
        run: cargo fmt --check

  coverage:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Run Coverage
        run: cargo tarpaulin --engine llvm --ignore-tests --out Xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: cobertura.xml

  docs_benchmark_audit:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: [setup, test]
    steps:
      - uses: actions/checkout@v3
      - name: Generate Documentation
        run: cargo doc --no-deps
      - name: Run Benchmarks
        run: cargo bench
      - name: Run Security Audit
        run: cargo audit
      - name: Upload Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-scanning-report
          path: gl-dependency-scanning-report.json
