name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  setup_rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set up Rust environment and tools
      - name: Set up Rust
        run: |
          rustc --version
          cargo --version
          rustup component add clippy rustfmt
          cargo install cargo-tarpaulin cargo-audit

  cargo_build_release:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - uses: actions/checkout@v3

      # Build the project in release mode without caching
      - name: Build with Cargo in Release Mode
        run: |
          cargo build --release

  run_tests_and_coverage:
    runs-on: ubuntu-latest
    needs: cargo_build_release
    steps:
      - uses: actions/checkout@v3

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      # Pull the prebuilt Docker image that sets up the application and database
      - name: Pull Docker image
        run: |
          docker pull your-docker-image:latest

      # Run tests and code coverage inside Docker container
      - name: Run Tests and Coverage inside Docker container
        run: |
          docker run --env-file .env.ci your-docker-image:latest \
          /bin/bash -c "\
            cargo test --release && \
            cargo tarpaulin --release --engine llvm --ignore-tests --out Xml"
          
  lint_and_format:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - uses: actions/checkout@v3

      # Lint and format code
      - name: Lint and Format
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check

  documentation_benchmarks_audit:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - uses: actions/checkout@v3

      # Generate documentation, run benchmarks, and audit dependencies
      - name: Documentation, Benchmarks, and Audit
        run: |
          cargo doc --no-deps
          cargo bench
          cargo audit
