name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  all_in_one:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Setup Rust environment and tools
      - name: Set up Rust
        run: |
          rustc --version && cargo --version
          rustup component add clippy rustfmt
          cargo install cargo-tarpaulin cargo-audit
          cargo install diesel_cli --no-default-features --features postgres
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Install PostgreSQL
      - name: Install PostgreSQL
        run: |
          apt-get update
          apt-get install -y postgresql

      # Configure PostgreSQL to use 'trust' authentication
      - name: Configure PostgreSQL Authentication
        run: |
          sed -i "s/peer/trust/g" /etc/postgresql/*/main/pg_hba.conf
          sed -i "s/md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
          service postgresql start

      # Create PostgreSQL Database
      - name: Setup PostgreSQL Database
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres_db
          ROCKET_ENV: test
        run: |
          # Create PostgreSQL database
          psql -U postgres -c "CREATE DATABASE postgres_db;"

          # Run migrations
          diesel migration run

          # Run tests
          cargo test

      # Lint and format code
      - name: Lint and Format
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check

      # Run code coverage
      - name: Run Coverage
        run: cargo tarpaulin --engine llvm --ignore-tests --out Xml

      # Generate documentation, run benchmarks, and audit dependencies
      - name: Documentation, Benchmarks, and Audit
        run: |
          cargo doc --no-deps
          cargo bench
          cargo audit
