name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:

jobs:
  setup_rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          source $HOME/.cargo/env

  build_and_test:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          cargo build --verbose
          cargo test --verbose

  lint_and_format:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint and Format
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check

  documentation_benchmarks_audit:
    runs-on: ubuntu-latest
    needs: setup_rust
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Documentation, Benchmarks, and Audit
        run: |
          cargo doc --no-deps
          cargo bench
          cargo audit
