name: Rust CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    strategy:
      matrix:
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-${{ matrix.toolchain }}-
      - name: Set up Rust
        run: rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/release

  lint-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Set up Rust
        run: rustup component add clippy
      - name: Lint
        run: cargo clippy -- -D warnings

  format-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Set up Rust
        run: rustup component add rustfmt
      - name: Check Format
        run: cargo fmt --check

  doc-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        run: cargo doc --no-deps
      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: target/doc

  benchmark-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: Benchmark
        run: cargo bench

  audit-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-
      - name: Install Cargo Audit
        run: cargo install cargo-audit
      - name: Audit
        run: cargo audit --json > gl-dependency-scanning-report.json
      - name: Upload Audit Report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-scanning-report
          path: gl-dependency-scanning-report.json

  coverage-code:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: build-test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cargo Tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Generate Coverage
        run: cargo tarpaulin --engine llvm --ignore-tests --out Xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: cobertura.xml
