name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
  schedule:
    - cron: '0 0 * * 0'  # Run the CI every Sunday at midnight

jobs:
  all_in_one:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v3

      # Setup Rust environment and tools
      - name: Set up Rust
        run: |
          rustc --version && cargo --version
          rustup component add clippy rustfmt
          cargo install cargo-tarpaulin cargo-audit
          cargo install diesel_cli --no-default-features --features postgres
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      # Build the project
      - name: Build
        run: cargo build

      # Set environment variables and run tests
      - name: Test with PostgreSQL
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres_db
          ROCKET_ENV: test
        run: |
          # Set up PostgreSQL service
          sudo service postgresql start
          psql -U postgres -c "CREATE DATABASE postgres_db;"
          
          # Run migrations
          diesel migration run

          # Run tests
          cargo test

      # Lint and format code
      - name: Lint and Format
        run: |
          cargo clippy -- -D warnings
          cargo fmt --check

      # Run code coverage
      - name: Run Coverage
        run: cargo tarpaulin --engine llvm --ignore-tests --out Xml

      # Generate documentation, run benchmarks, and audit dependencies
      - name: Documentation, Benchmarks, and Audit
        run: |
          cargo doc --no-deps
          cargo bench
          cargo audit
