name: Build and Release

on:
  push:
    tags:
      - 'v*'  # This triggers the action only when you push a new tag starting with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build in release mode
      run: cargo build --release

    - name: Upload release asset
      uses: actions/upload-artifact@v3
      with:
        name: rust_financial_manager
        path: target/release/rust_financial_manager

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/rust_financial_manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
